set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
syntax on
set number
set tabstop=4
filetype plugin indent on
set undofile
set undodir=~/.vim/undo/
"This check is probably unneccessary, but it's in here just in case this is
"auto-sourced by neovim
if !has('nvim')
	set viminfo+=n~/.vim/viminfo
endif
